name: todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^2.2.4
  shared_preferences: ^2.5.4
  dartz: ^0.10.1
  dio: ^5.9.2
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Lexend_Deca
      fonts:
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Black.ttf
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Bold.ttf
        - asset: assets/fonts/Lexend_Deca/LexendDeca-ExtraBold.ttf
        - asset: assets/fonts/Lexend_Deca/LexendDeca-ExtraLight.ttf
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Light.ttf
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Medium.ttf
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Regular.ttf
        - asset: assets/fonts/Lexend_Deca/LexendDeca-SemiBold.ttf
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Thin.ttf